version: 2

jobs:
  - docker:
      image: golang:1.13-buster
    template:
      name: go

publications:
  - url: https://pkg.go.dev/github.com/launchdarkly/go-configtypes
    description: documentation
